language: ruby
cache: bundler
rvm:
- 2.1.0
- 2.0.0
- 1.9.3
services:
- redis-server
notifications:
  email: false
  irc:
    channels:
      - ircs://irc.oftc.net:6697#akerl
    channel_key: sekrit
    template:
      - '%{repository}/%{branch}/%{build_number}: %{message} -- %{build_url}'
